apiVersion: bishoybasily.gmail.com/v1
kind: Fidelyo
metadata:
  name: fidelyo-service-y
  namespace: fcrd
spec:
  image: bishoybasily/service:fcrd-1.2
  port: 9090
  replicas: 3
  serviceType: LoadBalancer
  envVars:
    - name: MESSAGE
      value: Java loves kubernetes - service Y
