apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: fidelyos.bishoybasily.gmail.com
spec:
  group: bishoybasily.gmail.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: fidelyos
    singular: fidelyo
    kind: Fidelyo
    shortNames:
      - fd
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            image:
              type: string
            replicas:
              type: integer
            port:
              type: integer
            serviceType:
              type: string
            envVars:
              type: object
